### ISSUE TITLE
Update npm / nodejs

### ISSUE THREAD

**Issue by mikiline** [buanet/docker-iobroker#10]
please can you upgrade node to version 8.12.0 and npm to 6.4.1 of the container ?
some adapters need to upgrade and this container still work with 3.10.10

**Comment by rewegit** [comment]
I'd like to join you. Please update npm and nodejs. I can't update inside the container (docker exec). I always get an error:
"Cannot find module 'strip-ansi'" 
Thx for your great work!

**Comment by buanet** [comment]
Hi,
just published a new beta branch for node 8. There will be a new docker-tag named "node8beta" available on docker-hub in a few minutes. I only checked ioBroker starting up when using the new image, so no guarantee everything is working. :)
When upgrading an existing ioBroker installation or restoring a folder-backup from a node 6 installation please use "./reinstall.sh" to recompile installed adapters (see ioBroker Docu: http://www.iobroker.net/docu/?page_id=5106&lang=de).
Would be nice to get some feedback. Thx.

**Comment by willhoh** [comment]
Hi,
I have now switched to node8beta. I installed my sonoff-, Mi-Home, Telegram, Cloud, Js and node-red adapter and everything runs great. If you want more feedback, I will be happy to do it for you.

**Comment by rewegit** [comment]
I've been working with this change for two weeks. So far no problems have been noticed.

Adapter:
/opt/iobroker# iobroker list adapters
system.adapter.admin : admin - 3.5.10
system.adapter.discovery : discovery - 1.2.4
system.adapter.zigbee : zigbee - 0.7.7
system.adapter.alexa2 : alexa2 - 1.1.0
system.adapter.hm-rpc : hm-rpc - 1.7.8
system.adapter.hm-rega : hm-rega - 1.7.1
system.adapter.email : email - 1.0.4
system.adapter.javascript : javascript - 3.6.4
system.adapter.influxdb : influxdb - 1.6.2
system.adapter.node-red : node-red - 1.7.1
system.adapter.scenes : scenes - 1.1.0
system.adapter.tr-064 : tr-064 - 0.4.18
system.adapter.cloud : cloud - 2.6.2
system.adapter.web : web - 2.4.1
system.adapter.socketio : socketio - 2.1.1
system.adapter.rpi2 : rpi2 - 1.0.0
system.adapter.js2fs : js2fs - 0.1.5
system.adapter.openweathermap : openweathermap - 0.1.0

You may want to note that the image on ducker hub is created for amd64.
For arm, it must be recreated on the target host. (rock64 in my case)

thx for your great work

**Comment by buanet** [comment]
Thx for feedback. I just upgraded my own Installation (with Multihost) to node8. No problems so far.
Just waiting for some adapter updates to verify this is working too. After this I have to extend the documentation/ tutorial with some node6 > node8 upgrade hints for existing installations.
Think I will merge this to a new version 3 until the end of November.

**Comment by mikiline** [comment]
thx for great work.... 👍

**Comment by schmupu** [comment]
the node8beta works great. I had a few problems with the ./reinstall.sh script and I had to to some manual npm installs for a few adapters. But I would say, it is not a problem of this container.
One question, why node 8 and not node 10?

**Comment by buanet** [comment]
Sounds good, thx for the feedback.
As the official docu refers to node 8, this will be the next stop.
If you can name an adapter which (officially) requires node 10, I will create an additional beta and work on that too... :)

**Comment by buanet** [comment]
Released v2.0.0 with node8 as latest. Thx for your support.
